### ISSUE TITLE
Different coeftables from GLM and CRRao

### ISSUE THREAD

**Issue by ShouvikGhosh2048** [xKDR/CRRao.jl#64]
@sourish-cmi 
The following program gives different coeftables:

```julia
using CRRao, GLM, RDatasets
turnout = dataset("Zelig", "turnout");
crrao_model = fit(@formula(Vote ~ 0 + Age + Race + Income + Educate), turnout, LogisticRegression(), Logit());
glm_model = glm(@formula(Vote ~ 0 + Age + Race + Income + Educate), turnout, Binomial(), LogitLink());
crrao_coeftable = coeftable(crrao_model);
glm_coeftable = coeftable(glm_model);
println(crrao_coeftable, glm_coeftable)
```

I think this occurs because of
https://github.com/xKDR/CRRao.jl/blob/c9373ce0b02bb90e096df7d6093b4f9566f34023/src/frequentist/logistic_regression.jl#L2
Is this difference intentional?

**Comment by codetalker7** [comment]
In this example, when we do
```
formula = apply_schema(formula, schema(formula, data)) 
```
where `formula` is `@formula(Vote ~ 0 + Age + Race + Income + Educate)` and `data` is `turnout`, we get the following.
```
FormulaTerm
Response:
  Vote(continuous)
Predictors:
  0
  Age(continuous)
  Race(DummyCoding:2→1)
  Income(continuous)
  Educate(continuous)
``` 
So for the `Race` attribute, this returns a Dummy encoded variable. Since the `Race` attribute is taking two distinct values in the dataset (namely `white` and `others`), the Dummy encoded variable will use just one bit to represent these two values. For this reason, I believe the CRRao model returns only one coefficient for the `Race` attribute.

On the other hand, `GLM` is using two variables to represent the `Race` attribute (this might be the usual One Hot encoding). So I think we need to decide what default encoding scheme to use, and this might not be an error per say.

**Comment by ShouvikGhosh2048** [comment]
@sourish-cmi 
To get a similar result as GLM, we can make our model types extend RegressionModel in StatsAPI, and pass that type into apply_schema.

```Julia
using RDatasets, StatsBase, StatsModels
turnout = dataset("Zelig", "turnout");

struct ExampleRegressionType <: RegressionModel end

f = @formula(Vote ~ Age + Race + Income + Educate);
f = apply_schema(f, schema(f, turnout), ExampleRegressionType);
_,X = modelcols(f, turnout);
X

f = @formula(Vote ~ 1 + Age + Race + Income + Educate);
f = apply_schema(f, schema(f, turnout), ExampleRegressionType);
_,X = modelcols(f, turnout);
X

f = @formula(Vote ~ 0 + Age + Race + Income + Educate);
f = apply_schema(f, schema(f, turnout), ExampleRegressionType);
_,X = modelcols(f, turnout);
X
```

**Comment by sourish-cmi** [comment]
@ShouvikGhosh2048 

Your code is working fine. I think we don't need to define the `struct` for `ExampleRegressionType`, i.e.,

```Julia
struct ExampleRegressionType <: RegressionModel end
```
Regular `RegressionModel` would work just fine.

```Julia
f = @formula(Vote ~ Age + Race + Income + Educate);
f = apply_schema(f, schema(f, turnout), RegressionModel);
_,X = modelcols(f, turnout);
X

f = @formula(Vote ~ 1 + Age + Race + Income + Educate);
f = apply_schema(f, schema(f, turnout), RegressionModel);
_,X = modelcols(f, turnout);
X

f = @formula(Vote ~ 0 + Age + Race + Income + Educate);
f = apply_schema(f, schema(f, turnout), RegressionModel);
_,X = modelcols(f, turnout);
X
```

**Comment by sourish-cmi** [comment]
[PR](https://github.com/xKDR/CRRao.jl/pull/66) is created
